name: flutter_widget_from_html
version: 0.17.1
description: Flutter package to render html as widgets that supports hyperlink, image, audio, video, iframe and many other tags.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.32.0"
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.17.0
  html: ^0.15.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  # trick Flutter@3.22 to use chewie@1.7.5
  # otherwise it will install v1.8.7 which is in fact incompatible with Flutter@3.22
  # TODO: remove this when our minimum Flutter version >= 3.24
  chewie: ^1.7.5
  file:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  lint: any
  mocktail: ^1.0.0

flutter:
  assets:
    - test/images/

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

screenshots:
  - description: Demo rendering of HTML tags
    path: example/HelloWorldScreen1.gif
  - description: Demo rendering of HTML tags
    path: example/HelloWorldScreen2.gif
  - description: Demo rendering of HTML tags
    path: example/HelloWorldScreen3.gif

topics:
  - widget
  - html
  - css
  - fwfh
